package com.example.customerdataservice.web;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-08-09T21:38:24.106+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://web.customerdataservice.example.com/", name = "CustomerSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerSoapService {

    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://web.customerdataservice.example.com/", className = "com.example.customerdataservice.web.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://web.customerdataservice.example.com/", className = "com.example.customerdataservice.web.SaveCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.customerdataservice.web.Customer saveCustomer(

        @WebParam(name = "arg0", targetNamespace = "")
        com.example.customerdataservice.web.CustomerRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "customers", targetNamespace = "http://web.customerdataservice.example.com/", className = "com.example.customerdataservice.web.Customers")
    @ResponseWrapper(localName = "customersResponse", targetNamespace = "http://web.customerdataservice.example.com/", className = "com.example.customerdataservice.web.CustomersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.example.customerdataservice.web.Customer> customers()
;

    @WebMethod
    @RequestWrapper(localName = "customerById", targetNamespace = "http://web.customerdataservice.example.com/", className = "com.example.customerdataservice.web.CustomerById")
    @ResponseWrapper(localName = "customerByIdResponse", targetNamespace = "http://web.customerdataservice.example.com/", className = "com.example.customerdataservice.web.CustomerByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.customerdataservice.web.Customer customerById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );
}
